Repository rems-project/cerberus, pull requests merged in 2024-11, with the labels that each got.

#691 [CN] Fix `IT.free_vars` for pattern matches
  backend/cn/lib/indexTerms.ml
Labels: cn

#699 [CN-Exec/CN-Test-Gen] Generalize failure handling
  runtime/libcn/include/cn-executable/utils.h
  runtime/libcn/include/cn-testing/test.h
  runtime/libcn/src/cn-executable/alloc.c
  runtime/libcn/src/cn-executable/utils.c
  runtime/libcn/src/cn-testing/test.c
Labels: cn, CN spec testing

#704 Adjust caching in workflows
  .github/workflows/ci-cheri.yml
  .github/workflows/ci-cn-bench.yml
  .github/workflows/ci-cn-spec-testing.yml
  .github/workflows/ci-cn.yml
  .github/workflows/ci-pr-bench.yml.disabled
  .github/workflows/ci.yml
Labels: CI
