Repository rems-project/cerberus, pull requests merged in 2024-10, with the labels that each got.

#591 [CN-Exec] Add `free_all` for bump allocator
  runtime/libcn/include/cn-executable/alloc.h
  runtime/libcn/src/alloc.c
  runtime/libcn/src/hash_table.c
Labels: cn

#628 [CN-Exec] Fix min and max handling of `cn_bool`
  runtime/libcn/include/cn-executable/utils.h
Labels: cn

#630 [CN-Test-Gen] Portability fix for printing seeds
  runtime/libcn/src/cn-testing/test.c
Labels: cn, technical debt

#669 Fix #668 - pragma line loc info
  parsers/c/c_lexer.mll
Labels: bug, cn

#673 [CN-Test-Gen] Reset error message info between runs
  runtime/libcn/include/cn-executable/utils.h
  runtime/libcn/include/cn-testing/test.h
  runtime/libcn/src/cn-executable/utils.c
Labels: cn

#635 [CN-Exec/CN-Test-Gen] Generate functions for assuming ownership
  backend/cn/bin/main.ml
  backend/cn/lib/cn_internal_to_ail.ml
  backend/cn/lib/cn_internal_to_ail.mli
  backend/cn/lib/executable_spec_internal.ml
  backend/cn/lib/testGeneration/specTests.ml
  backend/cn/lib/testGeneration/specTests.mli
  backend/cn/lib/testGeneration/testGeneration.ml
  backend/cn/lib/testGeneration/testGeneration.mli
  runtime/libcn/include/cn-testing/dsl.h
  runtime/libcn/include/cn-testing/test.h
Labels: cn

#674 [CN-Test-Gen] Rewrite ownership and allocation checking
  backend/cn/lib/testGeneration/genCodeGen.ml
  backend/cn/lib/testGeneration/specTests.ml
  runtime/libcn/include/cn-testing/alloc.h
  runtime/libcn/include/cn-testing/dsl.h
  runtime/libcn/include/cn-testing/test.h
  runtime/libcn/src/cn-testing/gen_alloc.c
Labels: cn

#675 [CN-Exec/CN-Test-Gen] Add allocation checkpoints
  runtime/libcn/include/cn-executable/alloc.h
  runtime/libcn/include/cn-testing/dsl.h
  runtime/libcn/src/cn-executable/alloc.c
Labels: cn
