Repository rems-project/cerberus, pull requests merged in 2025-02, with the labels that each got.

#864 [CI] Trying to fix CI
  .github/workflows/ci-cheri.yml
  .github/workflows/ci.yml
Labels: CI

#865 [CI] Trying to CI take 2
  .github/workflows/ci.yml
Labels: CI

#867 [CN-Exec/CN-Test-Gen] Configurable trace granularity
  backend/cn/bin/main.ml
  backend/cn/lib/testGeneration/buildScript.ml
  backend/cn/lib/testGeneration/testGenConfig.ml
  backend/cn/lib/testGeneration/testGenConfig.mli
  runtime/libcn/include/cn-executable/utils.h
  runtime/libcn/src/cn-executable/utils.c
  runtime/libcn/src/cn-testing/test.c
Labels: cn, CN spec testing, CN-exec

#869 [CI] Trying to speed up Cerberus-CHERI
  .github/workflows/ci-cheri.yml
  .github/workflows/ci-cn-bench.yml
  .github/workflows/ci-cn-coq.yml
  .github/workflows/ci-cn-spec-testing.yml
  .github/workflows/ci-cn.yml
  .github/workflows/ci.yml
Labels: CI

#871 [CN-Test-Gen] More test case sizing strategies
  backend/cn/bin/main.ml
  backend/cn/lib/testGeneration/buildScript.ml
  backend/cn/lib/testGeneration/testGenConfig.ml
  backend/cn/lib/testGeneration/testGenConfig.mli
  runtime/libcn/include/cn-testing/test.h
  runtime/libcn/src/cn-testing/test.c
  tests/run-cn-test-gen.sh
Labels: cn, CN spec testing

#876 [CN-Test-Gen] Parallelize CI tests via `make -j`
  backend/cn/lib/testGeneration/buildScript.ml
  runtime/libcn/src/cn-testing/test.c
  tests/cn-test-gen/Makefile
  tests/cn-test-gen/run-single-test.sh
  tests/run-cn-test-gen.sh
Labels: cn, CI, CN spec testing

#877 [CN-Test-Gen] Various tweaks and nitpicks
  backend/cn/TESTING.md
  backend/cn/bin/main.ml
  backend/cn/lib/testGeneration/buildScript.ml
  backend/cn/lib/testGeneration/testGenConfig.ml
  backend/cn/lib/testGeneration/testGenConfig.mli
  backend/cn/lib/testGeneration/testGeneration.ml
  backend/cn/lib/testGeneration/testGeneration.mli
  runtime/libcn/include/cn-testing/test.h
  runtime/libcn/src/cn-testing/test.c
  tests/cn-test-gen/.gitignore
  tests/cn-test-gen/run-single-test.sh
Labels: cn, CN spec testing

#855 seq tests
  .github/workflows/ci-cn-spec-testing.yml
  backend/cn/bin/main.ml
  backend/cn/lib/testGeneration/seqTestGenConfig.ml
  backend/cn/lib/testGeneration/seqTestGenConfig.mli
  backend/cn/lib/testGeneration/seqTests.ml
  backend/cn/lib/testGeneration/seqTests.mli
  backend/cn/lib/testGeneration/testGeneration.ml
  backend/cn/lib/testGeneration/testGeneration.mli
  tests/cn-seq-test-gen/.gitignore
  tests/cn-seq-test-gen/src/abs.pass.c
  tests/cn-seq-test-gen/src/bst.pass.c
  tests/cn-seq-test-gen/src/ini_queue.fail.c
  tests/cn-seq-test-gen/src/runway.pass.c
  tests/cn-seq-test-gen/src/slf_sized_stack.fail.c
  tests/cn-seq-test-gen/src/slf_sized_stack.pass.c
  tests/cn-seq-test-gen/src/tutorial_queue.fail.c
  tests/cn-seq-test-gen/src/tutorial_queue.pass.c
  tests/run-cn-seq-test-gen.sh
Labels: enhancement, cn

#885 Ignore LibCN formatting PR for blame
  .git-blame-ignore-revs
Labels: cn, technical debt, CN spec testing, CN-exec
